# Generated by Django 5.2.3 on 2025-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('answer', models.CharField(choices=[('a', 'option1'), ('b', 'option2'), ('c', 'option3'), ('d', 'option4')], default='none', max_length=100)),
            ],
        ),
    ]
