# Generated by Django 5.2.3 on 2025-06-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_category_alter_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.category'),
        ),
    ]
