# Generated by Django 5.2.3 on 2025-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(max_length=1000),
        ),
    ]
